// Vietnamese UI text constants
// All app chrome is in Vietnamese. Marketing content (captions, prompts, AI output) stays per-post language.

export const T = {
  // ── Navigation ──
  nav_dashboard: "Trang chủ",
  nav_content: "Nội dung",
  nav_studio: "Studio",
  nav_brands: "Thương hiệu",
  nav_trash: "Thùng rác",
  logout: "Đăng xuất",

  // ── Common actions ──
  save: "Lưu",
  saving: "Đang lưu...",
  cancel: "Hủy",
  delete: "Xóa",
  create: "Tạo mới",
  edit: "Chỉnh sửa",
  duplicate: "Nhân bản",
  trash: "Xóa",
  generate: "Tạo hình",
  regenerate: "Tạo lại",
  generate_all: "Tạo tất cả hình",
  upload: "Tải lên",
  upload_save: "Tải lên & Lưu",
  download: "Tải xuống",
  approve: "Duyệt",
  import: "Nhập",
  export: "Xuất",
  copy: "Sao chép",
  close: "Đóng",
  back: "Quay lại",
  search: "Tìm kiếm",
  filter: "Lọc",
  clear: "Xóa bộ lọc",
  select_all: "Chọn tất cả",
  show_more: "Xem thêm",
  hide: "Ẩn",
  confirm: "Xác nhận",

  // ── Status messages ──
  saved: "Đã lưu!",
  deleted: "Đã xóa!",
  copied: "Đã sao chép!",
  generating: "Đang tạo...",
  uploading: "Đang tải lên...",
  loading: "Đang tải...",
  error: "Lỗi",
  success: "Thành công",
  failed: "Thất bại",
  not_found: "Không tìm thấy",
  no_data: "Chưa có dữ liệu",
  updated: "Đã cập nhật",
  imported: "Đã nhập!",
  generated: "Đã tạo hình!",
  approved: "Đã duyệt!",
  trashed: "Đã chuyển vào thùng rác",
  restored: "Đã khôi phục!",

  // ── Dashboard ──
  dash_title: "Apolo Content Studio",
  dash_content: "Nội dung",
  dash_content_hub: "Trung tâm nội dung",
  dash_content_hub_desc: "Bảng kanban, lịch & bộ lọc",
  dash_create: "Tạo bài mới",
  dash_create_desc: "Soạn bài với AI hoặc nhập JSON",
  dash_calendar: "Lịch",
  dash_calendar_desc: "Lên lịch nội dung trực quan",
  dash_studio: "Xưởng hình ảnh",
  dash_gen_banner: "Tạo banner",
  dash_gen_banner_desc: "Tạo banner Facebook",
  dash_batch: "Tạo hàng loạt",
  dash_batch_desc: "Tạo nhiều banner cùng lúc",
  dash_brands: "Thương hiệu",

  // ── Content Hub ──
  posts: "Bài viết",
  all_brands: "Tất cả",
  kanban: "Kanban",
  calendar: "Lịch",
  table: "Bảng",
  unscheduled: "Chưa lên lịch",
  today: "Hôm nay",

  // ── Content Create ──
  create_title: "Tạo bài mới",
  language: "Ngôn ngữ",
  remove: "Xóa",

  // ── Post Detail ──
  tab_content: "Nội dung",
  tab_image: "Hình ảnh",
  tab_settings: "Cài đặt",
  captions: "Caption",
  caption_vi: "Tiếng Việt",
  caption_en: "Tiếng Anh",
  banner_text: "Chữ trên banner",
  headline: "Tiêu đề chính",
  subline: "Dòng phụ",
  cta: "Nút CTA",
  tags: "Thẻ",
  no_tags: "Chưa có thẻ",
  add_tag: "Thêm thẻ...",
  new_tag: "Thẻ mới",
  visual_prompt: "Mô tả hình ảnh",
  style: "Phong cách",
  model: "Người mẫu",
  no_model: "Không dùng",
  post_type: "Loại bài",
  generated_images: "Hình đã tạo",
  image_versions: "Phiên bản hình",
  topic: "Chủ đề",
  content_type: "Loại nội dung",
  service_area: "Lĩnh vực",
  schedule: "Lịch đăng",
  info: "Thông tin",
  created_at: "Ngày tạo",
  updated_at: "Ngày sửa",

  // ── Studio ──
  studio_title: "Xưởng hình ảnh",
  settings_saved: "Cài đặt tự động lưu",
  brand: "Thương hiệu",
  logo: "Logo",
  logos: "Logo",
  include_logo: "Bao gồm logo khi tạo hình",
  models: "Người mẫu",
  references: "Hình tham khảo",
  visual_desc: "Mô tả hình ảnh",
  text_overlay: "Chữ trên hình",
  auto_fill: "Tự động điền",
  variations: "Gợi ý biến thể",
  gallery: "Thư viện",
  history: "Lịch sử",
  import_to_content: "Nhập vào nội dung",
  clear_history: "Xóa lịch sử",
  no_history: "Chưa có lịch sử. Tải lên hình để bắt đầu.",
  no_images: "Chưa có hình ảnh",
  banner_image: "Hình banner",

  // ── Brands ──
  brands_title: "Thương hiệu",
  new_brand: "Thương hiệu mới",
  ai_prompt: "Prompt AI",
  import_json: "Nhập JSON",
  identity: "Nhận diện",
  brand_id: "Mã thương hiệu",
  brand_name: "Tên thương hiệu",
  tagline: "Khẩu hiệu",
  industry: "Ngành nghề",
  voice_audience: "Giọng & Đối tượng",
  tone: "Giọng nói",
  target_audience: "Đối tượng mục tiêu",
  font_style: "Kiểu chữ",
  colors: "Bảng màu",
  primary: "Chính",
  secondary: "Phụ",
  accent: "Nhấn",
  add_model: "Thêm người mẫu",
  model_name: "Tên người mẫu",
  model_desc: "Mô tả (VD: Giám đốc, ảnh chân dung)",
  add_variant: "Thêm biến thể",
  multi_upload: "Tải nhiều",
  save_brand: "Lưu thương hiệu",
  delete_brand: "Xóa thương hiệu",
  select_brand: "Chọn hoặc tạo thương hiệu mới",
  no_brands: "Chưa có thương hiệu",
  description: "Mô tả",

  show_versions: "Xem phiên bản",
  trash_non_approved: "Xóa ảnh chưa duyệt",

  // ── Batch ──
  batch_title: "Tạo hàng loạt",
  copy_ai_prompt: "Sao chép prompt AI",
  save_to_sheet: "Lưu",
  has_logo: "Logo",
  has_model: "Người mẫu",
  has_ref: "Tham khảo",

  // ── AI Composer & Editor ──
  ai_composer: "Soạn bài bằng AI",
  ai_composer_desc: "Nhập giọng nói, bài mẫu và dữ liệu — AI soạn bài hoàn chỉnh",
  tone_of_voice: "Giọng nói",
  tone_custom_placeholder: "Mô tả giọng nói của bạn...",
  content_angle: "Góc nội dung",
  sample_posts_label: "Bài mẫu tham khảo",
  sample_posts_placeholder: "Dán 1-2 bài mẫu để AI học cách viết (cấu trúc, emoji, block liên hệ)...",
  facts_label: "Thông tin & dữ liệu",
  facts_placeholder: "Liệt kê thông tin: dịch vụ, giá, thời gian, điểm nổi bật...",
  compose_now: "Soạn bằng AI",
  composing: "Đang soạn...",
  load_template: "Tải template",
  save_as_template: "Lưu thành template",
  template_name_prompt: "Đặt tên cho template",
  template_saved: "Đã lưu template",
  template_deleted: "Đã xóa template",
  manage_templates: "Quản lý template",
  no_templates: "Chưa có template nào",
  load_brand_samples: "Nạp bài mẫu từ thương hiệu",
  // Editor toolbar
  toolbar_emoji: "Chèn emoji",
  toolbar_checklist: "Danh sách ✅",
  toolbar_numbered: "Danh sách số 1️⃣",
  toolbar_contact: "Khối liên hệ",
  toolbar_hashtags: "Hashtag",
  toolbar_divider: "Dòng phân cách",
  toolbar_clear: "Xóa caption",
  toolbar_clear_confirm: "Xóa toàn bộ caption?",
  // Brands sample posts
  brand_sample_posts: "Bài mẫu tham khảo",
  add_sample_post: "Thêm bài mẫu",
  sample_label_placeholder: "Nhãn (VD: Dịch vụ hợp đồng)",
  sample_text_placeholder: "Dán nội dung bài FB làm mẫu...",

  // ── Ads ──
  ads_campaign: "Quảng cáo",
  ads_enabled: "Bật quảng cáo",
  ads_name: "Tên chiến dịch",
  ads_objective: "Mục tiêu",
  ads_audience: "Đối tượng",
  ads_budget_per_day: "Ngân sách/ngày",
  ads_duration: "Số ngày chạy",
  ads_total_budget: "Tổng ngân sách",
  ads_landing_url: "Landing URL",
  ads_cta: "CTA quảng cáo",
  verify_text: "Duyệt Text",
  verify_image: "Duyệt Hình",

  // ── Filters ──
  sort_by: "Sắp xếp",
  advanced_filters: "Bộ lọc nâng cao",
  status: "Trạng thái",
  selected: "đã chọn",
  change_status: "Đổi trạng thái",
  bulk_delete: "Xóa hàng loạt",
  assign_tag: "Gán thẻ",
  deselect: "Bỏ chọn",
};
